# Generated by Django 5.2.4 on 2025-07-08 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_comment_is_shared_favorite_delete_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('video', 'user')},
        ),
    ]
